### PR TITLE
updated config for IPIM course

### PR DESCRIPTION
**Pull request by ngljcb**
changes:
- updated the teacher's list for algoritmi & strutture dati
- updated the teacher's list for finanza aziendali
- added elective course: logica per l'informatica

### CODE REVIEW

**Review by foxyseta — APPROVED** [review]
Nice! After the merge, Dependabot will open PRs to update this dependency in the other projects.

**Comment by foxyseta** [comment]
The conflicts are due to the PR being based on an extremely old commit. How about creating a new PR altogether on a new branch?

**Comment by ngljcb** [comment]
ok, i'll create a new branch then, thanks!

**Comment by foxyseta** [comment]
Closing in favor of #70.

**Pull request closed without merging**
